server:
  port: 9002
spring:
  application:
    name: config-client-test-xyy
  rabbitmq:
   host: 192.168.0.207  
eureka:
  client:
    service-url:
      defaultZone: http://xyy:123@192.168.0.36:8002/eureka/,http://xyy:123@192.168.0.36:8003/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'refresh'
